name: satstack
description: "Bitcoin stack tracker"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.5.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  connectivity_plus: ^5.0.0
  flutter_animate: ^4.1.1+1
  permission_handler: ^11.0.1
  local_auth: ^2.1.5
  flutter_secure_storage: ^8.0.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.2
  file_picker: ^10.3.3
  universal_html: ^2.2.3
  url_launcher: ^6.1.11
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  syncfusion_flutter_pdf: ^23.1.44
  csv: ^5.0.3
  open_file: ^3.3.3
  excel: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"